#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

RABBITMQ_IMAGE="rabbitmq"
RABBITMQ_IMAGE_VERSION=3.5.4-management
RABBITMQ_ROOT=/var/lib/dokku/services/rabbitmq

PLUGIN_DATA_ROOT=$RABBITMQ_ROOT
PLUGIN_SERVICE="RabbitMQ"
PLUGIN_IMAGE=$RABBITMQ_IMAGE
PLUGIN_IMAGE_VERSION=$RABBITMQ_IMAGE_VERSION

if ! docker images | grep -e "^$PLUGIN_IMAGE " | grep -q $PLUGIN_IMAGE_VERSION ; then
  docker pull $PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION
fi

mkdir -p $PLUGIN_DATA_ROOT || echo "Failed to create $PLUGIN_SERVICE directory"
chown dokku:dokku $PLUGIN_DATA_ROOT
